# Generated by Django 2.1.1 on 2018-09-23 15:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Invalid format. Valid format is composed of 10 or 11 digits.', regex='^((?:[1-9]{2})(?:[2-8]|9[1-9])[0-9]{7})$')])),
                ('destination', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Invalid format. Valid format is composed of 10 or 11 digits.', regex='^((?:[1-9]{2})(?:[2-8]|9[1-9])[0-9]{7})$')])),
            ],
            options={
                'verbose_name': 'call',
                'verbose_name_plural': 'calls',
            },
        ),
    ]
