# Generated by Django 2.1.1 on 2018-09-23 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('start', 'Start'), ('end', 'End')], default='start', max_length=5)),
                ('timestamp', models.DateTimeField()),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.Call')),
            ],
            options={
                'verbose_name': 'record',
                'verbose_name_plural': 'records',
            },
        ),
        migrations.AlterUniqueTogether(
            name='record',
            unique_together={('call', 'type')},
        ),
    ]
