# Generated by Django 2.1.1 on 2018-09-27 19:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180923_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'bill',
                'verbose_name_plural': 'bills',
            },
        ),
        migrations.AlterField(
            model_name='call',
            name='destination',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Invalid phone number. Valid format is composed of 10 or 11 digits. ie: AAXXXXXXXXX, where AA is the area code and XXXXXXXXX is the phone number', regex='(^[1-9]{2})([1-9]\\d{7,8}$)')]),
        ),
        migrations.AlterField(
            model_name='call',
            name='source',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Invalid phone number. Valid format is composed of 10 or 11 digits. ie: AAXXXXXXXXX, where AA is the area code and XXXXXXXXX is the phone number', regex='(^[1-9]{2})([1-9]\\d{7,8}$)')]),
        ),
        migrations.AddField(
            model_name='bill',
            name='call',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Call'),
        ),
    ]
